### ISSUE TITLE
Problema con implementazione istanza CrudAutoma nell'App component

### ISSUE THREAD

**Issue by FedericoRez** [ManuelBava/Crud-Ang-Gal#1]
![Immagine 2021-02-23 194323](https://user-images.githubusercontent.com/78588276/108891913-93ba9e00-760f-11eb-9ab3-5fb1f3b29109.png)
![Immagine 2021-02-23 194344](https://user-images.githubusercontent.com/78588276/108891918-94533480-760f-11eb-9e97-4e9f1810968b.png)
![Immagine 2021-02-23 194517](https://user-images.githubusercontent.com/78588276/108891919-94ebcb00-760f-11eb-9246-e6fcf5f9c31d.png)

**Comment by luca-lezzerini** [comment]
Dovete implementare l'interfaccia nel Component.ts. Dovete mettere il metodo entraInsìStatoRicerca()

**Comment by FedericoRez** [comment]
la classe component contiene implements Automabile(che è l'interfaccia con all'interno il metodo cosi come da senda foto) soltanto che non si vede per la finestra di errore 
![Immagine 2021-02-23 195833](https://user-images.githubusercontent.com/78588276/108893472-6969e000-7611-11eb-9fbd-458e3448db91.png)
...

**Comment by FedericoRez** [comment]
P.S
ignori il fatto che ho richiamato automa dopo la dichiarazione
![Immagine 2021-02-23 200027](https://user-images.githubusercontent.com/78588276/108893678-a7ff9a80-7611-11eb-83d0-c795d316f5f8.png)
... 
anche se lo scrivo senza richiamarlo nuovamente mi da comunque errore
